---
title: "Analysis"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)

theme = theme_minimal()

library(lme4)
library(jsonlite)
```

```{r}
read = function (x) {
  read_csv(paste("data/", x, sep=""), col_types = cols())
}
data =
  list.files("data/", pattern="*.csv") %>%
  map_df(~read(.))
```

```{r}
data
```


```{r}
dataf = data[, c("rt", "time_elapsed", "ppt", "recipient_sex", "metaphor", "response", "responses", "qtype")]

dataf = dataf %>% 
  group_by(ppt) %>%
  summarise(
    donation = response[qtype %in% "trial"],
    cond_sex = recipient_sex[1],
    cond_metaphor = metaphor[1],
    rt_1 = rt[1],
    rt_2 = rt[2],
    rt_3 = rt[3],
    rt_4 = rt[4],
    rt_5 = rt[5],
    rt_6 = rt[6],
    rt_7 = rt[7],
    rt_8 = rt[8],
    rt_9 = rt[9],
    rt_10 = rt[10],
    rt_11 = rt[11],
    rt_12 = rt[12],
    rt_13 = rt[13],
    rt_14 = rt[14],
    total_time = time_elapsed[14],
    urgent = factor(fromJSON(responses[qtype %in% "urgent"])$Q0, levels = seq(1,7)),
    serious = factor(fromJSON(responses[qtype %in% "serious"])$Q0, levels = seq(1,7)),
    sympathy = factor(fromJSON(responses[qtype %in% "sympathy"])$Q0, levels = seq(1,7)),
    peace = factor(fromJSON(responses[qtype %in% "peace"])$Q0, levels = seq(1,7)),
    guilty = factor(fromJSON(responses[qtype %in% "guilty"])$Q0, levels = seq(1,7)),
    gender = factor(fromJSON(responses[qtype %in% "demographics"])$Q0),
    education = factor(fromJSON(responses[qtype %in% "demographics"])$Q1),
    socioeconomic = factor(fromJSON(responses[qtype %in% "demographics"])$Q2),
    english = factor(fromJSON(responses[qtype %in% "demographics"])$Q3),
    age = fromJSON(responses[qtype %in% "age"])$Q0,
    feedback = fromJSON(responses[qtype %in% "feedback"])$Q0
    )
```

```{r}
head(dataf)
```

```{r}
dataf %>%
  group_by(cond_sex, cond_metaphor) %>%
  summarise(avg_donation = mean(donation)) %>%
  ggplot() + theme + geom_tile(aes(x = cond_sex, y = cond_metaphor, fill = avg_donation))
```


```{r}
ggplot(dataf) + theme +
  geom_density(aes(donation)) +
  labs(x = "Donation Amount", y = "Density", title = "Donation Amount Distribution") +
  lims(x = c(0,50))

ggplot(dataf) + theme +
  geom_density(aes(rt_1)) +
  geom_density(aes(rt_2)) +
  geom_density(aes(rt_3), color = "red") +
  labs(x = "Response Time", y = "Density", title = "Response Time Distributions")

ggplot(dataf) + theme +
  geom_density(aes(total_time))

ggplot(dataf) + theme +
  geom_bar(aes(urgent, group=1, y=..prop..)) +
  scale_x_discrete(drop = F) +
  labs(x = "Urgent", y = "Proportion", title = "Urgent Distribution", subtitle = "\"Her situation is urgent.\"")

ggplot(dataf) + theme +
  geom_bar(aes(serious, group=1, y=..prop..)) +
  scale_x_discrete(drop = F) +
  labs(x = "Serious", y = "Proportion", title = "Serious Distribution", subtitle = "\"Her situation is serious.\"")

ggplot(dataf) + theme +
  geom_bar(aes(sympathy, group=1, y=..prop..)) +
  scale_x_discrete(drop = F) +
  labs(x = "Sympathy", y = "Proportion", title = "Sympathy Distribution", subtitle = "\"Her situation is one I sympathize with.\"")

ggplot(dataf) + theme +
  geom_bar(aes(peace, group=1, y=..prop..)) +
  scale_x_discrete(drop = F) +
  labs(x = "Peace", y = "Proportion", title = "Peace Distribution", subtitle = "\"She can make peace with her experience.\"")

ggplot(dataf) + theme +
  geom_bar(aes(guilty, group=1, y=..prop..)) +
  scale_x_discrete(drop = F) +
  labs(x = "Guilty", y = "Proportion", title = "Guilty Distribution", subtitle = "\"She will feel guilty that she hasn’t done enough if she does not recover.\"")
```







